# Generated by Django 5.2.3 on 2025-06-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topupproduct',
            name='game',
        ),
        migrations.RemoveField(
            model_name='topuporder',
            name='product',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='TopUpOrder',
        ),
        migrations.DeleteModel(
            name='TopUpProduct',
        ),
    ]
