# Generated by Django 5.2.3 on 2025-06-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0006_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
