# Generated by Django 5.2.3 on 2025-06-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0009_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_game',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
